# Generated by Django 5.0.4 on 2024-05-12 07:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("creator", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Survey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "survey_title",
                    models.CharField(max_length=100, verbose_name="Заголовок опроса"),
                ),
                ("start_time", models.DateTimeField(verbose_name="Время начала")),
                ("end_time", models.DateTimeField(verbose_name="Время завершения")),
                (
                    "students",
                    models.ManyToManyField(
                        to=settings.AUTH_USER_MODEL, verbose_name="Студенты"
                    ),
                ),
                (
                    "test",
                    models.ManyToManyField(to="creator.anketa", verbose_name="Тесты"),
                ),
            ],
            options={
                "verbose_name": "Опрос",
                "verbose_name_plural": "Опросы",
            },
        ),
    ]
