# Generated by Django 5.0.4 on 2024-05-06 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("student", "0002_alter_studentanswer_answer_text"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="studentanswer",
            options={
                "verbose_name": "Ответ студента",
                "verbose_name_plural": "Ответы студента",
            },
        ),
    ]
